- src/lib.rs
This also breaks BIO_s_file which we need.
> Don't disable stdio

- src/lib.rs
This is only necessary when targetting MUSL but we don't use any of this
stuff anyway.
> Disable async APIs

- src/lib.rs
This skips man pages, which take a bunch of time to copy over since there are so many of them.
> Use `make install_sw` rather than `make install`

- .travis.yml
- src/lib.rs
`wasm32-unknown-unknown` is a bit harder, so I focused on emscripten first.
`emcc` is similar to `gcc`, so we can configure OpenSSL for `gcc` and it works.
However if we simply do that, we get linking errors when building the `openssl` executable because some symbols are defined twice. I have no idea what that happens.
The easiest way to disable building the `openssl` executable if to use `no-stdio`, so that's what I'm doing.
Tests unfortunately fail because of out-of-memory issues, but the ones which don't need a lot of memory all pass.
I didn't add any CI test because it's quite hard to test for emscripten on travis (building emscripten :-/). It should be doable with circle-ci if you think we should add CI.
> Add support for emscripten

- src/lib.rs
Share Cargo's jobserver with `make` so they can all build in parallel from the
same job pool.
> Enable parallel builds of OpenSSL on Unix

- src/lib.rs
Hi. I am cross compiling from x86_64-unknown-linux-gnu -> armv7-unknown-linux-musleabihf. I found I needed this small addition for things to work.
> Add support for armv7-unknown-linux-musleabihf target

- src/lib.rs
Rust supports 5 different android target and 4 other are in the list except armv7-linux-androideabi.
> add armv7-linux-androideabi to target list

- src/lib.rs
Looks like other platforms need it for cert loading!
> Only pass no-stdio on Android

- src/lib.rs
> Fix missing windres when cross building to i686-pc-windows-gnu

- src/lib.rs
very much like recent DragonflyBSD changes, on FreeBSD make is BSD make, calling gmake instead
> FreeBSD also uses BSD make, so need to call gmake instead

- src/lib.rs
When we build the source shouldn't need to copy .git to build it!
Closes #26
> Don't copy over .git directory to build dir

- src/lib.rs
Just in my case, this can ease my life:)
Install paths are generated that are windows escaped (C:\\for\\the\\way)
When cross compiling to my **mips** target i have GNU-tools working and c:/for/the/way is the way to go.
Use case of Doom: 
Cross compilation for an embedded target and to have the ability to switch between targets. 
Main development happens on the HOST and also testing, playground, debugging.
My solution so far is: 
cfg openssl-sys for linux vendor featured, patch crates-io and have this path local.
```
[target.'cfg(target_os = "linux")'.dependencies]
openssl-sys = { version = "0.9.12", features = ["vendored"] }
[patch.crates-io]
openssl-src = { path = './dependencies/openssl-src-111.2.1+1.1.1b' }
```
full on IDE:
When you have to fiddle with configuration files between …
> cross compilation on windows for mips

- src/lib.rs
This adds support for Aarch64 builds with musl libc.
> Add aarch64-unknown-linux-musl target

- src/lib.rs
I'm not sure how to test this, please let me know if you have a tip on how to get started!
Hacks:
- Remove `-arch xxx` arg supplied by `cargo-lipo`; OpenSSL already adds it and complains
- Remove and split up `-isysroot xxx` arg supplied by `cargo-lipo`; OpenSSL already adds it and complains, but needs parts of it during *build* phase
> add aarch64-apple-ios target support

- src/lib.rs
When `CROSS_COMPILE` is set `cc::Build` is using it to generate compiler command. However `./Configure` of OpenSSL is using it again which has as a result the environment variable to the prepended twice.
For example `CROSS_COMPILE=arm-none-linux-gnueabi` will result to
`arm-none-linux-gnueabiarm-none-linux-gnueabi-gcc`
> Fix cross compilation when `CROSS_COMPILE` env is set

- src/lib.rs
When building it for ppcle64, it fails to build tests:
```
test/libtestutil.a(tests.o): In function `test_time_t_eq':
/workspace/openssl-src-rs/target/debug/build/testcrate-0895561f72afc32c/out/openssl-build/build/src/test/testutil/tests.c:443: undefined reference to `ASN1_TIME_compare'
test/libtestutil.a(tests.o): In function `test_time_t_ne':
/workspace/openssl-src-rs/target/debug/build/testcrate-test0895561f72afc32c//outlibtestutil.a/(openssltests.o): -In buildfunction/ `buildtest_time_t_eq/':
src//workspace//openssl-testutilsrc-rs//targettests.c/:debug444/:build/ testcrate-0895561f72afc32c/undefinedout/ openssl-reference buildto/build/ src/`test/ASN1_TIME_comparetestutil/'tests.c
:443test: /undefined referencelibtestutil.a( totests.o `)ASN1_TIME_compare:'
test/libtestutil.aIn(tests.o …
```
> only build necessary target

- src/lib.rs
```
Caused by:
process didn't exit successfully: `.../rust-bootstrap/work-aarch64/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage1-tools/release/build/openssl-sys-4b2d35028bf73953/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
--- stderr
thread 'main' panicked at 'don't know how to configure OpenSSL for aarch64-unknown-freebsd', .../rust-bootstrap/work-aarch64/rustc-1.40.0-src/vendor/openssl-src/src/lib.rs:178:18
```
> Add support for non-x86 archs on FreeBSD

- src/lib.rs
I have performed at least basic testing of this change in two contexts:
* on a Linux system, in a Rust CI docker image, cross building an illumos compiler
* on an illumos system, building a patched version of `rustup` for native illumos use
Resolves #51
> support for illumos systems

- src/lib.rs
Or I could list all the FreeBSD targets...
> Use gmake by default on all FreeBSD or DragonFlyBSD targets

- src/lib.rs
As part of the preparation for rust-lang/rust#55553, add support for the Solaris-like illumos target.
> Add support for illumos triple

- src/lib.rs
Addresses #61 
I wasn't sure of the best way to test this, but it's a small fix in any case.
> Do not overwrite AR and RANLIB env vars if set

- src/lib.rs
I met link error when updating in grpc-rs which is a binding lib to grpc-core. And I found openssl-src remove `engine` on no matter what platform.
Related PR: https://github.com/tikv/grpc-rs/pull/466
Signed-off-by: Xintao <hunterlxt@live.com>
> Add engine support for linux-gnu

- src/lib.rs
cc v1.0.58 broke the macOS build by including the "-arch" flag in the
default set of compiler flags. Strip it out, like we do for iOS targets.
Closes #66.
> Fix build on macOS with latest cc crate

- Cargo.toml
- ci/run.sh
- src/lib.rs
This commit disables by default a few of the weaker cryptographical algorithms into
a "weak-crypto" feature as well as some of the less used algorithms into
their own specific features.
These algorithms are not directly exposed through the rust-openssl crate.
The compilation of these can be re-enabled by selecting the desired features.
This should slightly reduce build time and library size.
Signed-off-by: Petre Eftime <petre.eftime@gmail.com>
I've tested this feature by building this crate with cargo, and by modifying a local rust-openssl repo to use my local clone as the source for openssl-src, and ran `cargo test --features vendored`, with and without these features specified in Cargo.toml.
> add optional features for less used algorithms

- src/lib.rs
FreeBSD PowerPC64LE is a new target.
This is needed to cross-build cargo.
> Add FreeBSD powerpc64le support

- src/lib.rs
I'm working on an Intel Quark which actually uses such an old instruction set.
Adding the `i586-unknown-linux-musl` target was all that was required to get a successful TLS connection with reqwest, compiled using the i586 toolchain provided by rust-embedded/cross.
I haven't explicitly tested the `i586-unknown-linux-gnu` target but I have no reason to think it won't work, as musl is usually the trickier target.
> i586 support

- src/lib.rs
Support targets `armv7-unknown-linux-gnueabi` & `armv7-unknown-linux-musleabi`
> Support targets `armv7-unknown-linux-gnueabi/musleabi`

- src/lib.rs
It seems that `wasm32-unknown-unknown` and `wasm32-unknown-emscripten` are already supported. This PR adds `wasm32-wasi` to this list.
> Make it compile for wasm32-wasi

- src/lib.rs
Moved the argument and added it close to the "no-dso", as it's seems it's a "related" configuration switch.
> Moved "no-shared" so that also windows statically link to the libraries

- .github/workflows/main.yml
- README.md
- src/lib.rs
issue #59
For Windows users, if the `OPENSSL_RUST_USE_NASM` environment variable is set, the assembly language routines will be enabled.
Tested on Windows 10 64bit (20H2), VS Community 2019 (16.9.1), rustc 1.50.0 (stable-x86_64-pc-windows-msvc), NASM version 2.15.05.
> add nasm support for msvc

- src/lib.rs
This is needed to support cargo cross-build for 32-bit powerpc on FreeBSD.
> Add FreeBSD powerpc support

- Cargo.toml
Bump to https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1l
> Bump to openssl 1.1.1l

- Cargo.toml
- src/lib.rs
On amd64, trying to compile a project (https://github.com/deltachat/deltachat-core-rust) that uses openssl-sys and vendors openssl via openssl-src, gets me this:
```
thread 'main' panicked at 'OpenSSL library directory does not exist: deltachat-core-rust/target/debug/build/openssl-sys-72260f2c868a930d/out/openssl-build/install/lib', openssl-sys/build/main.rs:66:9
stack backtrace:
0: rust_begin_unwind
at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
1: std::panicking::begin_panic_fmt
at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
2: build_script_main::main
3: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
This is solved by passing …
> Upgrade to OpenSSL v3.0.0

- Cargo.toml
Otherwise we're still sitting at 12M which is too big for crates.io
> Try excluding the fuzz corpora from crates.io

- Cargo.toml
- src/lib.rs
The provider ends up bundled into libcrypto.a, and loading the provider at runtime seems to work. The legacy provider is required to interface with things like PKCS#12 archives constructed with the default settings of earlier OpenSSL releases.
> Allow the legacy provider to be enabled

- ci/run.sh
These lines should no longer be necessary.  The default XCode is now 13.1 (and I believe the default SDK is macos 12.0).  I believe these were added since at the time the default xcode did not support aarch64-apple-darwin.
> Fix aarch64-apple-darwin CI

- src/lib.rs
When meta-rust is used for compiling openssl-sys it fails with the
following error:
| error: failed to run custom build command for `openssl-sys v0.9.61`
|
| Caused by:
|   process didn't exit successfully: `/home/builder/src/base/build/tmp/work/x86_64-linux/cargo-deny-native/0.9.1-r0/build/target/release/build/openssl-sys-ec38bc05b130195f/build-script-main` (exit code: 101)
|   --- stdout
|   cargo:rustc-cfg=const_fn
|   cargo:rerun-if-env-changed=X86_64_LINUX_OPENSSL_NO_VENDOR
|   X86_64_LINUX_OPENSSL_NO_VENDOR unset
|   cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
|   OPENSSL_NO_VENDOR unset
|
|   --- stderr
|   thread 'main' panicked at 'don't know how to configure OpenSSL for x86_64-linux', /home/builder/src/base/build/tmp/work/x86_64-linux/cargo-deny-native/0.9.1-r0/cargo_home/bitbak …
> Support bitbake's x86_64-linux

- src/lib.rs
As pointed out in #140 otherwise certificates and configure is by
default looked up in the directory of the build machine itself which is
often a writable path. Instead switch the configuration option back to
the default recommended in openssl's `INSTALL.md`
Closes #140
> Configure `--openssldir` to its default location

- src/lib.rs
As pointed out in #140 otherwise certificates and configure is by
default looked up in the directory of the build machine itself which is
often a writable path. Instead switch the configuration option back to
the default recommended in openssl's `INSTALL.md`
> [1.1.1] Configure `--openssldir` to its default location 

- Cargo.toml
https://github.com/openssl/openssl/releases/tag/openssl-3.0.6
> Bump to 3.0.6

- src/lib.rs
The GCC convention is that if the toolchain is named `$target-gnu-gcc`, then ranlib and ar will be available as `$target-gnu-gcc-ranlib` and `$target-gnu-gcc-ar` respectively. The code as written would infer them to be `$target-gnu-{ranlib,ar}`, which won't work.
I'm not sure why the code that existed was written the way it was -- I don't know of any GCC toolchains where the `-gcc` is stripped out in the name of ranlib/ar. The file listing on Debian's [GCC 6.x] and [GCC 10.x] all show the binaries using the `$target-gnu-gcc-$bin` format, as does Arch Linux's [GCC 12.x].
This error appears to also be present in the `cc` crate. There, the `-gcc` prefix is always stripped ([1][cc1], [2][cc2]), and then `-ar` is [appended]. But its saving grace is that it also checks if the resulting binary …
> Correctly infer ranlib/ar from cross-gcc

- Cargo.toml
- src/lib.rs
Note that `Command::get_program` and `Command::get_args` both stabilized in Rust 1.57.0, and so implicitly bump this crate's MSRV.
Depends on rust-lang/cc-rs#763.
Replaces #164.
> Use cc for ar/ranlib detection

- src/lib.rs
Some powerpc builds (notably Freescale QoriQ used in a few Synology NAS products) identifies as `gnuspe`. When it comes to compiling things like openssl, it seems the compiler itself deals with this additional detail and so these builds can just use `linux-ppc` as far as I can tell.
I did a simple test locally on my Synology NAS, and there doesn't seem to be any immediate problems adding this.
PS.
What is the policy for adding this kind of changes to both this branch and the main branch?
> Add match for powerpc-unknown-linux-gnuspe

- src/lib.rs
This fixes the use of ARFLAGS and RANLIBFLAGS.
The check for ARFLAGS was inverted, and was only ever giving an empty string for ARFLAGS.
AFAICT, the OpenSSL Makefile does not support RANLIBFLAGS. This updates it so that the flags get stuffed in with RANLIB.
> Fix RANLIB and ARFLAGS

- Cargo.toml
Looks like the 3.1 release tipped the scales to this otherwise being larger than 10MB
> Omit new submodules from uploaded crate

- Cargo.toml
https://github.com/openssl/openssl/releases/tag/openssl-3.1.1
> Bump to 3.1.1

- src/lib.rs
As was included in the release/111 branch in #179
> Add match for powerpc-unknown-linux-gnuspe in main branch

- Cargo.toml
The last release on 1.1 branch (https://github.com/alexcrichton/openssl-src-rs/pull/208 for README update)
> Bump to 1.1.1w

- README.md
And clarification about major crate version being API/ABI compat version.
> OpenSSL 1.1.1 EOL

- .github/workflows/main.yml
- ci/docker/wasm32-wasi/Dockerfile
- ci/run.sh
- src/lib.rs
This accidentally worked before but `crypto/uid.c` references nonexistent functions in the WASI SDK which no longer works with more recent versions of Clang in an updated WASI SDK. Currently WASI SDK I think has a bug when compiled against the latest version of LLVM (pulled in with updated rustc) which causes CI failures as well.
I've updated the configuration here to pull in a newer WASI SDK which exposes the failure to build with `crypto/uid.c`, but I unfortunately don't have time to track this further right now.
> Disable WASI on CI

- src/lib.rs
Closes #118 
Without this patch, cross compilation on MSVC seems to directly embed backslashes from the prefix argument as various string constants in a C file via defines, like `ENGINESDIR`. This causes a build failure, as these backslashes get picked up as escape sequences.
Windows GNU targets are not affected by this issue, as they already do something similar to this patch within `sanitize_sh`.
I think this issue is caused by OpenSSL using the unix makefile template for cross-building to Linux, which I believe is not capable of escaping backslashes in the prefix argument. I believe that this is why a normal MSVC build works and why cross builds fail.
I have tested that this on Windows 11; this patch allows me to cross compile from `x86_64-pc-windows-msvc` to `x86_64-unknown-linux-gnu` …
> Fix MSVC Host Cross Compilation

- Cargo.toml
- src/lib.rs
Still working on reducing the size of the crate, a lof of big stuff was added.
> Bump to 3.2.0

- src/lib.rs
This patch remaps `loongarch64` to `linux-generic64` to disable vectors. (Guess it is not available when explicitly specified as `linux64-loongarch64`
> [111] loongarch64: Maps to linux-generic64

- src/lib.rs
This patch remaps `loongarch64` to `linux-generic64` to disable vectors. (Guess it is not available when explicitly specified as `linux64-loongarch64`
> [300] loongarch64: Maps to linux-generic64

- Cargo.toml
- src/lib.rs
Plus some fixes I needed to build this locally
> Bump OpenSSL to 3.2.1

- Cargo.toml
- src/lib.rs
This adds support for kTLS, but will not be enabled by default and will need to be set by the application with `SSL_OP_ENABLE_KTLS`.
> Add ktls feature

- src/lib.rs
Refusing to copy symlinks
breaks the build under <https://github.com/nix-community/naersk>.
Fixes #235
> Do not refuse to copy symlinks in build script

- src/lib.rs
Two new targets have been added with Windows 7 as their baseline: x86_64-win7-windows-msvc and i686-win7-windows-msvc. They are starting as Tier 3 targets, meaning that the Rust codebase has support for them but we don't build or test them automatically. Once these targets reach Tier 2 status, they will be available to use via rustup.
https://blog.rust-lang.org/2024/02/26/Windows-7.html
> Support new tier 3 `*-win7-windows-msvc` targets

- src/lib.rs
this allows wrappers like sccache to work properly
> use cc_env instead of path to set the CC configure variable

- src/lib.rs
In my testing, this was enough to enable support for the [x86_64-pc-windows-gnullvm](https://doc.rust-lang.org/rustc/platform-support/pc-windows-gnullvm.html) target with [llvm-mingw](https://github.com/mstorsjo/llvm-mingw). Without this change, an error is raised because the target is unknown.
> Add support for x86_64-pc-windows-gnullvm

- Cargo.toml
- src/lib.rs
Unless I'm mistaken, DSO support has no correlation with building shared libraries.
Without DSO support:
* engine support is automatically disabled(according to the docs).
* FIPS modules are not loadable, which typically come from validated compiled versions or the OS vendor.
> Default enable DSO API to support FIPS module

- src/lib.rs
Required to compile on openbsd -current with a snapdragon X elite cpu
> Add aarch64-unknown-openbsd to lib.rs

- src/lib.rs
Because [Cargo's formatting of build errors is very noisy](https://github.com/rust-lang/cargo/issues/10159) users struggle to understand what is causing the build to fail.
Here's a [recent case where the failure reason was simple, but the user could not see it](https://users.rust-lang.org/t/in-alpine-rust-can-not-link-ssl-library/117576/5) through all the noise.
----
```diff
Compiling openssl-sys v0.9.103 (~/openssl-sys/openssl-sys)
+The following warnings were emitted during compilation:
+
+warning: openssl-sys@0.9.103: configuring OpenSSL build: Command 'perl' not found. Is perl installed?
+
error: failed to run custom build command for `openssl-sys v0.9.103 (~/openssl-sys/openssl-sys)`
note: To improve backtraces for build dependencies, set the …
```
> Surface the failing command's name from the build error dump

- Cargo.toml
Updating to the most recent release.
> Bump OpenSSL to 3.4.0

- src/lib.rs
I'm honestly pretty confused as to how this was working previously - unless no-module is set, you'll end up with a legacy provider dynamic object that needs to exist in the openssldir: https://github.com/openssl/openssl/issues/17679
Tested here: https://github.com/sfackler/rust-openssl/pull/2331
Closes #257
> Set no-module to fix legacy provider

- Cargo.toml
- src/lib.rs
Allow SSLv3 to be enabled for versions of openssl where it's disabled by default (specifically OpenSSL 3.5)
Enable the underlying `ssl3` feature flag. In my own testing, the `ssl3-method` command was also necessary.
I tested this locally with my application to confirm that SSLv3 could be successfully negotiated.
> feat: expose configuration for SSLv3
